version: "3.8"
services:
  app:
    build:
      args:
        user: sd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sudahdigital
    container_name: sudahdigital-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sudahdigital

  nginx:
    image: nginx:alpine
    container_name: sudahdigital-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sudahdigital

networks:
  sudahdigital:
    driver: bridge

